import jsPDF from "jspdf";
import "jspdf-autotable";
import { STAGE_LABELS, SEGMENT_LABELS, OPENING_TYPE_LABELS } from "@/lib/constants";
import { formatMXN } from "@/lib/feasibility";

declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export function generateDealPDF(deal: any, tasks: any[]) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Header
  doc.setFillColor(17, 17, 17);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("AURORA DevOS MX — Investment Memo", 14, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), 14, 22);

  // Deal name + stage
  doc.setTextColor(17, 17, 17);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(deal.name, 14, 40);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${deal.city || ""}, ${deal.state || ""} • Stage: ${STAGE_LABELS[deal.stage] || deal.stage} • Score: ${deal.score_total || 0}/100`, 14, 47);

  // Key details table
  const details = [
    ["Segment", SEGMENT_LABELS[deal.segment] || deal.segment || "-"],
    ["Opening Type", OPENING_TYPE_LABELS[deal.opening_type] || deal.opening_type || "-"],
    ["Rooms", `${deal.rooms_min || "?"} - ${deal.rooms_max || "?"}`],
    ["Coordinates", deal.lat && deal.lon ? `${deal.lat.toFixed(4)}, ${deal.lon.toFixed(4)}` : "-"],
    ["Address", deal.address || "-"],
  ];

  doc.autoTable({
    startY: 52,
    head: [["Field", "Value"]],
    body: details,
    theme: "plain",
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [245, 245, 245], textColor: [50, 50, 50], fontStyle: "bold" },
    margin: { left: 14, right: 14 },
  });

  // Tasks
  const pendingTasks = tasks.filter(t => t.status !== "done").slice(0, 3);
  if (pendingTasks.length > 0) {
    const lastY = (doc as any).lastAutoTable?.finalY || 90;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 17, 17);
    doc.text("Next Steps", 14, lastY + 10);

    doc.autoTable({
      startY: lastY + 14,
      head: [["Task", "Due Date"]],
      body: pendingTasks.map(t => [t.title, t.due_date || "-"]),
      theme: "plain",
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [245, 245, 245], textColor: [50, 50, 50], fontStyle: "bold" },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by AURORA DevOS MX • Confidential", 14, 287);

  doc.save(`${deal.name.replace(/\s+/g, "_")}_Memo.pdf`);
}
